import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/Feed'
import { Header } from '../components/Header'
import Modal from '../components/Modal'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Smartmikey Instagram 2.0 build</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Modal />
      {/* Header */}
      <Header />
      {/* Feeds */}
      <Feed />
      {/* Footer */}

    </div>
  )
}
